FROM python:3.12-alpine

RUN apk add --no-cache iputils

WORKDIR /app

COPY agent/pinger.py /app/pinger.py
COPY hosts /app/hosts

RUN sed -i 's/\r$//' /app/hosts

ENTRYPOINT ["python", "/app/pinger.py"]
