apiVersion: 1

datasources:
  - name: InfluxDB
    uid: ping-influx
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ${INFLUX_DB}
    isDefault: true
    editable: false
