apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ${INFLUX_DB}
    user: ${INFLUX_USER}
    secureJsonData:
      password: ${INFLUX_PASS}
    jsonData:
      httpMode: POST
      timeInterval: "5s"
    isDefault: true
    editable: true
